//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeBot.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeBot.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MazeBot&gt;
        ///	&lt;MazeDefinition X=&quot;8&quot; Y=&quot;6&quot;&gt;
        ///		&lt;Walls&gt;
        ///			&lt;WallTile X=&quot;1&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;2&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;3&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;6&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/Walls&gt;
        ///	&lt;/MazeDefinition&gt;
        ///	&lt;Game&gt;
        ///		&lt;EndPoints&gt;
        ///			&lt;Start X=&quot;1&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;Goal X=&quot;5&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/EndPoints&gt;
        ///	&lt;/Game&gt;
        ///&lt;/MazeBot&gt;.
        /// </summary>
        internal static string sCheckInitXml {
            get {
                return ResourceManager.GetString("sCheckInitXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MazeBot&gt;
        ///	&lt;MazeDefinition X=&quot;8&quot; Y=&quot;6&quot;&gt;
        ///		&lt;Walls&gt;
        ///			&lt;WallTile X=&quot;1&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;2&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;3&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;6&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/Walls&gt;
        ///	&lt;/MazeDefinition&gt;
        ///	&lt;errGame&gt;
        ///		&lt;errEndPoints&gt;
        ///			&lt;Start X=&quot;1&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;Goal X=&quot;5&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/errEndPoints&gt;
        ///	&lt;/errGame&gt;
        ///&lt;/MazeBot&gt;.
        /// </summary>
        internal static string sErrorEndPointsXml {
            get {
                return ResourceManager.GetString("sErrorEndPointsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MazeBot&gt;
        ///	&lt;MazeDefinition X=&quot;8&quot; Y=&quot;6&quot;&gt;
        ///		&lt;errWalls&gt;
        ///			&lt;WallTile X=&quot;1&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;2&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;3&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;6&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/errWalls&gt;
        ///	&lt;/MazeDefinition&gt;
        ///	&lt;Game&gt;
        ///		&lt;EndPoints&gt;
        ///			&lt;Start X=&quot;1&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;Goal X=&quot;5&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/EndPoints&gt;
        ///	&lt;/Game&gt;
        ///&lt;/MazeBot&gt;.
        /// </summary>
        internal static string sErrorWallsXml {
            get {
                return ResourceManager.GetString("sErrorWallsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MazeBot&gt;
        ///	&lt;MazeDefinition X=&quot;8&quot; Y=&quot;6&quot;&gt;
        ///		&lt;Walls&gt;
        ///			&lt;WallTile X=&quot;1&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;2&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;3&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;6&quot;/&gt;
        ///			&lt;WallTile X=&quot;6&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/Walls&gt;
        ///	&lt;/MazeDefinition&gt;
        ///	&lt;Game&gt;
        ///		&lt;EndPoints&gt;
        ///			&lt;Start X=&quot;1&quot; Y=&quot;1&quot;/&gt;
        ///			&lt;Goal X=&quot;6&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/EndPoints&gt;
        ///	&lt;/Game&gt;
        ///&lt;/MazeBo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sNoSolutionXml {
            get {
                return ResourceManager.GetString("sNoSolutionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MazeBot&gt;
        ///	&lt;MazeDefinition X=&quot;8&quot; Y=&quot;6&quot;&gt;
        ///		&lt;Walls&gt;
        ///			&lt;WallTile X=&quot;1&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;2&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;3&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;3&quot;/&gt;
        ///			&lt;WallTile X=&quot;4&quot; Y=&quot;2&quot;/&gt;
        ///			&lt;WallTile X=&quot;5&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;6&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;5&quot;/&gt;
        ///			&lt;WallTile X=&quot;7&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/Walls&gt;
        ///	&lt;/MazeDefinition&gt;
        ///	&lt;Game&gt;
        ///		&lt;EndPoints&gt;
        ///			&lt;Start X=&quot;1&quot; Y=&quot;1&quot;/&gt;
        ///			&lt;Goal X=&quot;6&quot; Y=&quot;6&quot;/&gt;
        ///		&lt;/EndPoints&gt;
        ///	&lt;/Game&gt;
        ///&lt;/MazeBot&gt;.
        /// </summary>
        internal static string sSampleXml {
            get {
                return ResourceManager.GetString("sSampleXml", resourceCulture);
            }
        }
    }
}
